<!--
#=============================================================================
# Illusion Web Server v1.0
#
# by Bruno Quint, Jan 2010
#-----------------------------------------------------------------------------
# This file is part of the package called Illusion. Please, read LICENSE.txt
# file for information about copyrights.
#-----------------------------------------------------------------------------
# This file holds the graphical interface that will store the information
# regarding to the detector.
#=============================================================================
-->   
   
<!------------------------- Detector Parameters ----------------------------->
<td valign="top"><table>

    <tr><td colspan="2"><b>Detector</b></td></tr>

    <tr><td align="left">Width:</td>
        <td align="right">
        <input type="text" name="width" size=5 value="1600"></td>
        <td align="left">pixels</td></tr>

    <tr><td align="left">Height:</td>
        <td align="right">
        <input type="text" name="height" size=5 value="1600"></td>
        <td align="left">pixels</td></tr>

    <tr><td align="left">Pixel size:</td>
        <td align="right">
        <input type="text" name="pixel_size" size=5 value="16"></td>
        <td align="left">microns</td></tr>

    <tr><td align="left">Binning:</td>
        <td align="right">
        <input type="text" name="binning" size=5 value="4"></td>
        <td align="left">pixels</td></tr>

</table></td>
<!--------------------------------------------------------------------------->