<!--
#=============================================================================
# Illusion Web Server v1.0
#
# by Bruno Quint, Jan 2010
#-----------------------------------------------------------------------------
# This file is part of the package called Illusion. Please, read LICENSE.txt
# file for information about copyrights.
#=============================================================================
-->

<td bgcolor="<?php print("$White"); ?>" width=20% align=center valign=center>
    <img src="./images/illusion-logo.gif" width=50%></img>
</td>

<td valign="middle">
    <h1>Illusion - A Fabry-Perot Data-Cube Sinthesyzer</h1>
    <hr><hr width=40% align="left">
</td>