#!/usr/bin/env python
import argparse
import configparser
import pkg_resources
import sys


def main():

    # Read arguments from the command line
    parser = argparse.ArgumentParser(
        description="Illusion - Fabry-Perot Data-Cube Simulator."
    )

    parser.add_argument('-c', '--config', type=str, default=None,
                        help="Input config file containing relevant information"
                             " needed to simulate a data-cube.")

    args = parser.parse_args()

    # Read configuration file
    icon_path = pkg_resources.resource_filename(
        'illusion', 'default/standard_configuration.ini')
    print(icon_path)


if __name__ == '__main__':
    main()

